### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [chadmmiles/project10#1]
This is looking really good, apart from one thing I'd like updated. It looks like your CSS for the menu is making the errors all show up inline, instead of in a nice list. Can you update the styling to make sure those rules are only targeting the navigation menu?
### Optional updates

I told you in class you don't have to worry about validating the address because it would have involved a good deal of research. This happens to be a validation I've done before though and once you know how to do it, it's actually easier than one might think with the `geocoder` gem. All you should have to do is:

Add the `geocoder` gem to your `Gemfile`.

``` ruby
# Gemfile

gem 'geocoder'
```

Install the gem, then add latitude and longitude attributes to your `Listing` model.

``` bash
bundle install
rails generate migration AddLatitudeAndLongitudeToListings latitude:float longitude:float
rake db:migrate
```

Add this code to your model file and you're set up for very nice address validations, checked against Google's Maps API!

``` ruby
# app/models/listing.rb

geocoded_by :address
before_validation :geocode, if: ->(listing){ listing.address.present? && (listing.latitude.blank? || listing.address_changed?) }

validate :valid_address

def valid_address
  return if latitude
  errors.add :address, "isn't a valid address according to Google Maps"
end
```

Note that this allows only 2,500 address checks per day, so if your app grows to where you need more than that, then you'll have to [apply for a Premier API key and configure `geocoder` to use it](https://github.com/alexreisner/geocoder#street-address-services).

**Comment by chadmmiles** [comment]
I've updated this, but will push it to my heroku app once I update my project 11 as well since I have them on the same app and want to keep the updated version live.

**Comment by chadmmiles** [comment]
All set!

**Comment by chrisvfritz** [comment]
:+1: Looks good.
